/**
 * This class is generated by jOOQ
 */
package com.nearce.chatcraft.db.schema.tables;


import com.nearce.chatcraft.db.schema.CcDb;
import com.nearce.chatcraft.db.schema.Keys;
import com.nearce.chatcraft.db.schema.tables.records.VerifiedUsersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerifiedUsers extends TableImpl<VerifiedUsersRecord> {

	private static final long serialVersionUID = 1450403004;

	/**
	 * The reference instance of <code>cc_db.verified_users</code>
	 */
	public static final VerifiedUsers VERIFIED_USERS = new VerifiedUsers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VerifiedUsersRecord> getRecordType() {
		return VerifiedUsersRecord.class;
	}

	/**
	 * The column <code>cc_db.verified_users.id</code>.
	 */
	public final TableField<VerifiedUsersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cc_db.verified_users.mc_uuid</code>.
	 */
	public final TableField<VerifiedUsersRecord, String> MC_UUID = createField("mc_uuid", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>cc_db.verified_users.client_uuid</code>.
	 */
	public final TableField<VerifiedUsersRecord, String> CLIENT_UUID = createField("client_uuid", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>cc_db.verified_users</code> table reference
	 */
	public VerifiedUsers() {
		this("verified_users", null);
	}

	/**
	 * Create an aliased <code>cc_db.verified_users</code> table reference
	 */
	public VerifiedUsers(String alias) {
		this(alias, VERIFIED_USERS);
	}

	private VerifiedUsers(String alias, Table<VerifiedUsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private VerifiedUsers(String alias, Table<VerifiedUsersRecord> aliased, Field<?>[] parameters) {
		super(alias, CcDb.CC_DB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<VerifiedUsersRecord, Integer> getIdentity() {
		return Keys.IDENTITY_VERIFIED_USERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<VerifiedUsersRecord> getPrimaryKey() {
		return Keys.KEY_VERIFIED_USERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<VerifiedUsersRecord>> getKeys() {
		return Arrays.<UniqueKey<VerifiedUsersRecord>>asList(Keys.KEY_VERIFIED_USERS_PRIMARY, Keys.KEY_VERIFIED_USERS_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerifiedUsers as(String alias) {
		return new VerifiedUsers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public VerifiedUsers rename(String name) {
		return new VerifiedUsers(name, null);
	}
}
