/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/**
 * This class is generated by jOOQ
 */
package com.nearce.gamechatter.db.schema;


import com.nearce.gamechatter.db.schema.tables.VerifiedUsers;
import com.nearce.gamechatter.db.schema.tables.records.VerifiedUsersRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>cc_db</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<VerifiedUsersRecord, Integer> IDENTITY_VERIFIED_USERS = Identities0.IDENTITY_VERIFIED_USERS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<VerifiedUsersRecord> KEY_VERIFIED_USERS_PRIMARY = UniqueKeys0.KEY_VERIFIED_USERS_PRIMARY;
	public static final UniqueKey<VerifiedUsersRecord> KEY_VERIFIED_USERS_UUID = UniqueKeys0.KEY_VERIFIED_USERS_UUID;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<VerifiedUsersRecord, Integer> IDENTITY_VERIFIED_USERS = createIdentity(VerifiedUsers.VERIFIED_USERS, VerifiedUsers.VERIFIED_USERS.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<VerifiedUsersRecord> KEY_VERIFIED_USERS_PRIMARY = createUniqueKey(VerifiedUsers.VERIFIED_USERS, VerifiedUsers.VERIFIED_USERS.ID);
		public static final UniqueKey<VerifiedUsersRecord> KEY_VERIFIED_USERS_UUID = createUniqueKey(VerifiedUsers.VERIFIED_USERS, VerifiedUsers.VERIFIED_USERS.MC_UUID, VerifiedUsers.VERIFIED_USERS.CLIENT_UUID);
	}
}
