/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/**
 * This class is generated by jOOQ
 */
package com.nearce.gamechatter.db.schema;


import com.nearce.gamechatter.db.schema.tables.VerifiedUsers;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cc_db
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table cc_db.verified_users
	 */
	public static final VerifiedUsers VERIFIED_USERS = com.nearce.gamechatter.db.schema.tables.VerifiedUsers.VERIFIED_USERS;
}
