/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/**
 * This class is generated by jOOQ
 */
package com.nearce.gamechatter.db.schema.tables.records;


import com.nearce.gamechatter.db.schema.tables.VerifiedUsers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerifiedUsersRecord extends UpdatableRecordImpl<VerifiedUsersRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = 590553727;

	/**
	 * Setter for <code>cc_db.verified_users.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cc_db.verified_users.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cc_db.verified_users.mc_uuid</code>.
	 */
	public void setMcUuid(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cc_db.verified_users.mc_uuid</code>.
	 */
	public String getMcUuid() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cc_db.verified_users.client_uuid</code>.
	 */
	public void setClientUuid(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cc_db.verified_users.client_uuid</code>.
	 */
	public String getClientUuid() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return VerifiedUsers.VERIFIED_USERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return VerifiedUsers.VERIFIED_USERS.MC_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return VerifiedUsers.VERIFIED_USERS.CLIENT_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getMcUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getClientUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerifiedUsersRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerifiedUsersRecord value2(String value) {
		setMcUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerifiedUsersRecord value3(String value) {
		setClientUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerifiedUsersRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VerifiedUsersRecord
	 */
	public VerifiedUsersRecord() {
		super(VerifiedUsers.VERIFIED_USERS);
	}

	/**
	 * Create a detached, initialised VerifiedUsersRecord
	 */
	public VerifiedUsersRecord(Integer id, String mcUuid, String clientUuid) {
		super(VerifiedUsers.VERIFIED_USERS);

		setValue(0, id);
		setValue(1, mcUuid);
		setValue(2, clientUuid);
	}
}
