/**
 * This class is generated by jOOQ
 */
package com.nearce.chatcraft.db.schema;


import com.nearce.chatcraft.db.schema.tables.VerifiedUsers;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cc_db
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table cc_db.verified_users
	 */
	public static final VerifiedUsers VERIFIED_USERS = com.nearce.chatcraft.db.schema.tables.VerifiedUsers.VERIFIED_USERS;
}
